config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create' 
  get    '/logout', to: 'sessions#destroy' # temp until nav bar
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:new, :create]
  resources :lists, only: [:index, :create, :edit, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy

  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
    render html: 'hello, world!'
  end

  private
    def logged_in_user
      redirect_to root_url unless logged_in?
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :logged_in_user, only: :index
  before_action :set_list, only: [:edit, :update, :destroy]

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
      redirect_to lists_path
    end
  end

  def index
    @lists = List.where(user_id: current_user.id)
    @list = List.new()
  end

  def edit
  end

  def destroy
    @list.destroy
    redirect_to lists_url
  end

  def update
    @list.update(list_params)
    redirect_to lists_path
  end

  private
    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name, :description, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to lists_url
    else
      flash[:danger] = "Incorrect email/password"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  private
    # Prevents requests from accessing addition attributes on model
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    # Logs in the given user
    def log_in(user)
        session[:user_id] = user.id
    end

    # Logs out the current user
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    # Returns the current logged-in user (if any)
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    # Returns true if the user is logged in, false otherwise
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_list.html.erb
<li id="list-<%= list.id %>">
  <%=list.user.name%>: 
  <%=list.name %> -
  <%=list.description%>
  <%= link_to "delete", list, method: :delete %>
  <%= link_to "edit", edit_list_path(list) %>
</li>

app/views/lists/edit.html.erb
<%= form_for(@list) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>

  <%= f.submit 'Save', class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<ul class="lists">
  <% @lists.each do |list| %>
    <%= render list %>
  <% end %>
</ul>

<%= form_for(@list) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>

  <%= f.submit 'Add List', class: "btn btn-primary" %>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <div class="container">
    <h1>Welcome to ToDos</h1>
    <h2>Sverige urskiljde sig som en oberoende och enad stat under medeltiden.</h2>
    <div class="text-center">
      <%= link_to "Sign up!", signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign up</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit 'Create account', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>